export const PROTOSS = [
  {
    name: "probe",
    image: "/images/imgProtoss/probe.png",
    mana: 1,
    health: 1,
    attack: 1,
    price: 1,
  },
  {
    name: "zealot",
    image: "/images/imgProtoss/zealot.png",
    mana: 1,
    health: 2,
    attack: 2,
    price: 3,
  },
  {
    name: "stalker",
    image: "/images/imgProtoss/stalker.png",
    mana: 2,
    health: 3,
    attack: 2,
    price: 3,
  },
  {
    name: "colossus",
    image: "/images/imgProtoss/colossus.png",
    mana: 2,
    health: 3,
    attack: 3,
    price: 4,
  },
  {
    name: "carrier",
    image: "/images/imgProtoss/carrier.png",
    mana: 2,
    health: 4,
    attack: 3,
    price: 5,
  },
];
