export const PROTOSS = [
  {
    name: "probe",
    image: "/images/imgProtoss/probe.png",
    health: 1,
    mana: 1,
    attack: 1,
    price: 1,
  },
  {
    name: "zealot",
    image: "/images/imgProtoss/zealot.png",
    health: 2,
    mana: 1,
    attack: 2,
    price: 2,
  },
  {
    name: "stalker",
    image: "/images/imgProtoss/stalker.png",
    health: 2,
    mana: 2,
    attack: 3,
    price: 3,
  },
  {
    name: "colossus",
    image: "/images/imgProtoss/colossus.png",
    health: 5,
    mana: 3,
    attack: 3,
    price: 5,
  },
  {
    name: "carrier",
    image: "/images/imgProtoss/carrier.png",
    health: 6,
    mana: 3,
    attack: 3,
    price: 6,
  },
];
