export const TERRAN = [
  {
    name: "KSM",
    image: "/images/imgTerran/KSM.png",
    mana: 1,
    health: 1,
    attack: 1,
    price: 1,
  },
  {
    name: "marine",
    image: "/images/imgTerran/marine.png",
    mana: 1,
    health: 2,
    attack: 1,
    price: 2,
  },
  {
    name: "hellion",
    image: "/images/imgTerran/hellion.png",
    mana: 1,
    health: 1,
    attack: 2,
    price: 3,
  },
  {
    name: "marauder",
    image: "/images/imgTerran/marauder.png",
    mana: 1,
    health: 3,
    attack: 2,
    price: 5,
  },
  {
    name: "viking",
    image: "/images/imgTerran/viking.png",
    mana: 2,
    health: 4,
    attack: 2,
    price: 6,
  },
  {
    name: "banshee",
    image: "/images/imgTerran/banshee.png",
    mana: 2,
    health: 3,
    attack: 4,
    price: 7,
  },
  {
    name: "tank",
    image: "/images/imgTerran/tank.png",
    mana: 2,
    health: 4,
    attack: 4,
    price: 8,
  },
  {
    name: "ghost",
    image: "/images/imgTerran/ghost.png",
    mana: 3,
    health: 1,
    attack: 8,
    price: 9,
  },
  {
    name: "thor",
    image: "/images/imgTerran/thor.png",
    mana: 3,
    health: 8,
    attack: 3,
    price: 11,
  },
  {
    name: "batcruiser",
    image: "/images/imgTerran/batcruiser.png",
    mana: 3,
    health: 9,
    attack: 4,
    price: 13,
  },
];
