export const TERRAN = [
  {
    name: "KSM",
    image: "/images/imgTerran/KSM.png",
    mana: 1,
    health: 1,
    attack: 1,
    price: 1,
  },
  {
    name: "marine",
    image: "/images/imgTerran/marine.png",
    mana: 1,
    health: 2,
    attack: 1,
    price: 2,
  },
  {
    name: "hellion",
    image: "/images/imgTerran/hellion.png",
    mana: 1,
    health: 2,
    attack: 2,
    price: 3,
  },
  {
    name: "fireman",
    image: "/images/imgTerran/fireman.png",
    mana: 2,
    health: 3,
    attack: 2,
    price: 3,
  },
  {
    name: "maroder",
    image: "/images/imgTerran/maroder.png",
    mana: 2,
    health: 3,
    attack: 3,
    price: 4,
  },
];
