export const ZERG = [
  {
    name: "drone",
    image: "/images/imgZerg/drone.png",
    mana: 1,
    health: 1,
    attack: 1,
    price: 1,
  },
  {
    name: "zergling",
    image: "/images/imgZerg/zerling.png",
    mana: 1,
    health: 1,
    attack: 1,
    price: 1,
  },
  {
    name: "roach",
    image: "/images/imgZerg/roach.png",
    mana: 1,
    health: 2,
    attack: 1,
    price: 2,
  },
  {
    name: "gidral",
    image: "/images/imgZerg/gidral.png",
    mana: 1,
    health: 3,
    attack: 1,
    price: 3,
  },
  {
    name: "queen",
    image: "/images/imgZerg/queen.png",
    mana: 1,
    health: 4,
    attack: 1,
    price: 4,
  },
  {
    name: "mutalisk",
    image: "/images/imgZerg/mutalisk.png",
    mana: 1,
    health: 3,
    attack: 2,
    price: 5,
  },
  {
    name: "baneling",
    image: "/images/imgZerg/baneling.png",
    mana: 2,
    health: 1,
    attack: 6,
    price: 6,
  },
  {
    name: "host",
    image: "/images/imgZerg/host.png",
    mana: 2,
    health: 5,
    attack: 2,
    price: 7,
  },
  {
    name: "brood",
    image: "/images/imgZerg/brood.png",
    mana: 3,
    health: 6,
    attack: 3,
    price: 9,
  },
  {
    name: "ultralisk",
    image: "/images/imgZerg/ultralisk.png",
    mana: 3,
    health: 8,
    attack: 4,
    price: 12,
  },
];
