export const ZERG = [
  {
    name: "drone",
    image: "/images/imgZerg/drone.png",
    mana: 1,
    health: 1,
    attack: 1,
    price: 1,
  },
  {
    name: "zergling",
    image: "/images/imgZerg/zerling.png",
    mana: 1,
    health: 1,
    attack: 1,
    price: 1,
  },
  {
    name: "roach",
    image: "/images/imgZerg/roach.png",
    mana: 1,
    health: 2,
    attack: 1,
    price: 2,
  },
  {
    name: "gidral",
    image: "/images/imgZerg/gidral.png",
    mana: 1,
    health: 3,
    attack: 1,
    price: 3,
  },
  {
    name: "mutalisk",
    image: "/images/imgZerg/mutalisk.png",
    mana: 1,
    health: 3,
    attack: 2,
    price: 5,
  },
];
